# Generated by Django 4.1 on 2022-09-18 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2, verbose_name=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('release_date', models.DateField()),
            ],
        ),
    ]
