# Generated by Django 4.1 on 2022-09-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_watchlistmovies_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistmovies',
            name='review',
            field=models.TextField(default='-'),
        ),
    ]
